app = "discord-presence-api"
primary_region = "gru"

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[env]
  PORT = "3001"
