services:
  - type: web
    name: discord-presence-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: PORT
        value: 3001
      - key: DISCORD_TOKEN
        sync: false
